//! Tauri IPC command handlers, output-reader loop, and streaming event bridge.
//!
//! # Safety & Security Architecture
//! 1. The frontend never selects or supplies session IDs; IDs are generated by the native core.
//! 2. Shell paths and executables cannot be supplied arbitrarily by the frontend.
//! 3. All input payloads are bounded (`MAX_WRITE_PAYLOAD_BYTES`).
//! 4. Terminal output is read as raw bytes without UTF-8 lossy conversion or ANSI parsing.
//! 5. Output-reader threads operate independently without holding manager-level locks.
//! 6. Termination events (`terminal://exit`) use atomic guards to guarantee at most one exit event.

use crate::error::{Result, TerminalError};
use crate::terminal::manager::TerminalSessionManager;
use crate::terminal::types::{
    BytePayload, CloseTerminalSessionInput, CreateTerminalSessionInput, ExitReason,
    ResizeTerminalInput, TerminalErrorEvent, TerminalErrorOperation, TerminalExitEvent,
    TerminalOutputEvent, TerminalSessionInfo, WriteTerminalInput,
};
use std::io::Read;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

/// Hard maximum input payload size accepted for terminal write operations (64 KiB).
///
/// Prevents memory exhaustion and unresponsiveness caused by oversized IPC writes.
pub const MAX_WRITE_PAYLOAD_BYTES: usize = 64 * 1024;

/// Bounded buffer size for reading PTY output chunks (16 KiB).
///
/// Balances I/O throughput with responsive, low-latency streaming across the IPC bridge.
pub const PTY_READ_BUFFER_BYTES: usize = 16 * 1024;

/// Event name for streaming PTY raw byte output.
pub const EVENT_OUTPUT: &str = "terminal://output";

/// Event name for session termination.
pub const EVENT_EXIT: &str = "terminal://exit";

/// Event name for session errors.
pub const EVENT_ERROR: &str = "terminal://error";

/// Categorization of PTY read loop outcomes.
#[derive(Debug, PartialEq, Eq)]
pub enum ReaderReadResult {
    /// Bytes were read successfully from the PTY.
    Bytes(usize),
    /// PTY stream reached EOF (child process exited normally).
    Eof,
    /// Expected close-related I/O condition (e.g. EIO upon slave closure on Unix).
    ExpectedClose,
    /// Unexpected I/O error occurred during reading.
    UnexpectedError(String),
}

/// Validates that an input write payload is non-empty and within the size limit.
pub fn validate_write_payload(data: &[u8]) -> Result<()> {
    if data.is_empty() {
        return Err(TerminalError::EmptyPayload);
    }
    if data.len() > MAX_WRITE_PAYLOAD_BYTES {
        return Err(TerminalError::PayloadTooLarge {
            size: data.len(),
            max: MAX_WRITE_PAYLOAD_BYTES,
        });
    }
    Ok(())
}

/// Determines whether an I/O error corresponds to normal PTY closure upon child process exit.
pub fn is_expected_pty_close_error(err: &std::io::Error) -> bool {
    #[cfg(unix)]
    {
        // On Unix, reading from a master PTY after slave closure typically returns EIO (error code 5)
        if err.raw_os_error() == Some(5) {
            return true;
        }
    }

    matches!(
        err.kind(),
        std::io::ErrorKind::UnexpectedEof
            | std::io::ErrorKind::BrokenPipe
            | std::io::ErrorKind::ConnectionReset
    )
}

/// Pure classification helper for PTY reader loop iterations.
pub fn classify_read_result(result: &std::io::Result<usize>) -> ReaderReadResult {
    match result {
        Ok(0) => ReaderReadResult::Eof,
        Ok(n) => ReaderReadResult::Bytes(*n),
        Err(err) if is_expected_pty_close_error(err) => ReaderReadResult::ExpectedClose,
        Err(err) => ReaderReadResult::UnexpectedError(err.to_string()),
    }
}

/// Emits a `terminal://exit` event if one has not already been emitted for this session.
pub fn emit_exit_once(
    app_handle: &tauri::AppHandle,
    session_id: &str,
    exit_guard: &Arc<AtomicBool>,
    reason: ExitReason,
    exit_code: Option<i32>,
) {
    if !exit_guard.swap(true, Ordering::SeqCst) {
        use tauri::Emitter;
        let exit_payload = TerminalExitEvent {
            session_id: session_id.to_string(),
            exit_code,
            reason,
        };
        let _ = app_handle.emit(EVENT_EXIT, &exit_payload);
    }
}

/// Spawns a dedicated native OS thread to read output from the PTY.
pub fn spawn_output_reader(
    session_id: String,
    mut reader: Box<dyn Read + Send>,
    app_handle: tauri::AppHandle,
    exit_guard: Arc<AtomicBool>,
) -> Result<()> {
    let thread_name = format!("pty-reader-{}", &session_id);
    std::thread::Builder::new()
        .name(thread_name)
        .spawn(move || {
            run_reader_loop(&session_id, &mut *reader, &app_handle, &exit_guard);
        })
        .map_err(|e| TerminalError::ReaderSetupFailed(e.to_string()))?;

    Ok(())
}

/// Internal loop executed on the dedicated PTY reader thread.
fn run_reader_loop(
    session_id: &str,
    reader: &mut (dyn Read + Send),
    app_handle: &tauri::AppHandle,
    exit_guard: &Arc<AtomicBool>,
) {
    use tauri::Emitter;
    let mut buffer = [0u8; PTY_READ_BUFFER_BYTES];

    loop {
        let res = reader.read(&mut buffer);
        match classify_read_result(&res) {
            ReaderReadResult::Bytes(n) => {
                let event_payload = TerminalOutputEvent {
                    session_id: session_id.to_string(),
                    data: buffer[..n].to_vec(),
                };
                if let Err(err) = app_handle.emit(EVENT_OUTPUT, &event_payload) {
                    eprintln!("terminal://output emit error for {session_id}: {err}");
                    break;
                }
            }
            ReaderReadResult::Eof => {
                emit_exit_once(
                    app_handle,
                    session_id,
                    exit_guard,
                    ExitReason::ReaderEof,
                    None,
                );
                break;
            }
            ReaderReadResult::ExpectedClose => {
                emit_exit_once(
                    app_handle,
                    session_id,
                    exit_guard,
                    ExitReason::Closed,
                    None,
                );
                break;
            }
            ReaderReadResult::UnexpectedError(err_msg) => {
                let error_payload = TerminalErrorEvent {
                    session_id: Some(session_id.to_string()),
                    code: "IO_ERROR".to_string(),
                    message: err_msg,
                    operation: TerminalErrorOperation::Read,
                };
                let _ = app_handle.emit(EVENT_ERROR, &error_payload);
                emit_exit_once(
                    app_handle,
                    session_id,
                    exit_guard,
                    ExitReason::ChildWaitError,
                    None,
                );
                break;
            }
        }
    }
}

/* ========================================================================== */
/* Tauri IPC Commands                                                         */
/* ========================================================================== */

/// Creates a new terminal session, spawns its shell, and starts its dedicated output reader.
#[tauri::command]
pub fn terminal_create_session(
    app_handle: tauri::AppHandle,
    manager: tauri::State<'_, TerminalSessionManager>,
    input: Option<CreateTerminalSessionInput>,
) -> Result<TerminalSessionInfo> {
    let input = input.unwrap_or_default();
    let session_info = manager.create_session(input)?;
    let session_id = session_info.session_id.clone();

    let reader = match manager.get_session_reader(&session_id) {
        Ok(r) => r,
        Err(err) => {
            let _ = manager.close(CloseTerminalSessionInput {
                session_id: session_id.clone(),
            });
            return Err(err);
        }
    };

    let exit_guard = match manager.get_session_exit_guard(&session_id) {
        Ok(g) => g,
        Err(err) => {
            let _ = manager.close(CloseTerminalSessionInput {
                session_id: session_id.clone(),
            });
            return Err(err);
        }
    };

    if let Err(err) = spawn_output_reader(session_id.clone(), reader, app_handle, exit_guard) {
        let _ = manager.close(CloseTerminalSessionInput {
            session_id: session_id.clone(),
        });
        return Err(err);
    }

    Ok(session_info)
}

/// Writes byte-safe input to a terminal session's PTY stdin.
#[tauri::command]
pub fn terminal_write(
    session_id: Option<String>,
    data: Option<BytePayload>,
    input: Option<WriteTerminalInput>,
    manager: tauri::State<'_, TerminalSessionManager>,
) -> Result<()> {
    let (target_id, target_payload) = match (input, session_id, data) {
        (Some(i), _, _) => (i.session_id, i.data),
        (None, Some(id), Some(d)) => (id, d),
        _ => return Err(TerminalError::EmptyPayload),
    };

    let bytes = target_payload.as_bytes();
    validate_write_payload(bytes)?;
    manager.write_bytes(&target_id, bytes)
}

/// Resizes a terminal session's PTY window dimensions.
#[tauri::command]
pub fn terminal_resize(
    session_id: Option<String>,
    cols: Option<u16>,
    rows: Option<u16>,
    input: Option<ResizeTerminalInput>,
    manager: tauri::State<'_, TerminalSessionManager>,
) -> Result<()> {
    let resize_input = match (input, session_id, cols, rows) {
        (Some(i), _, _, _) => i,
        (None, Some(id), Some(c), Some(r)) => ResizeTerminalInput {
            session_id: id,
            cols: c,
            rows: r,
        },
        _ => {
            return Err(TerminalError::InvalidDimensions {
                cols: cols.unwrap_or(0),
                rows: rows.unwrap_or(0),
            })
        }
    };

    manager.resize(resize_input)
}

/// Closes a terminal session, terminates its child process, and frees in-memory state.
#[tauri::command]
pub fn terminal_close_session(
    app_handle: tauri::AppHandle,
    session_id: Option<String>,
    input: Option<CloseTerminalSessionInput>,
    manager: tauri::State<'_, TerminalSessionManager>,
) -> Result<()> {
    let target_id = match (input, session_id) {
        (Some(i), _) => i.session_id,
        (None, Some(id)) => id,
        (None, None) => return Err(TerminalError::SessionNotFound(String::new())),
    };

    let (exit_code, exit_guard) = manager.close_session(&target_id)?;
    emit_exit_once(&app_handle, &target_id, &exit_guard, ExitReason::Closed, exit_code);

    Ok(())
}

/// Retrieves metadata for a specific terminal session.
#[tauri::command]
pub fn terminal_session_info(
    session_id: Option<String>,
    input: Option<CloseTerminalSessionInput>,
    manager: tauri::State<'_, TerminalSessionManager>,
) -> Result<TerminalSessionInfo> {
    let target_id = match (input, session_id) {
        (Some(i), _) => i.session_id,
        (None, Some(id)) => id,
        (None, None) => return Err(TerminalError::SessionNotFound(String::new())),
    };

    manager.session_info(&target_id)
}

/// Lists metadata for all active terminal sessions.
#[tauri::command]
pub fn terminal_list_sessions(
    manager: tauri::State<'_, TerminalSessionManager>,
) -> Result<Vec<TerminalSessionInfo>> {
    Ok(manager.list_sessions())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::ErrorKind;

    #[test]
    fn test_validate_write_payload_empty() {
        assert!(matches!(
            validate_write_payload(&[]),
            Err(TerminalError::EmptyPayload)
        ));
    }

    #[test]
    fn test_validate_write_payload_oversized() {
        let oversized = vec![b'x'; MAX_WRITE_PAYLOAD_BYTES + 1];
        assert!(matches!(
            validate_write_payload(&oversized),
            Err(TerminalError::PayloadTooLarge { .. })
        ));
    }

    #[test]
    fn test_validate_write_payload_boundary() {
        let exact_max = vec![b'x'; MAX_WRITE_PAYLOAD_BYTES];
        assert!(validate_write_payload(&exact_max).is_ok());

        let small = b"echo 'hello'\n";
        assert!(validate_write_payload(small).is_ok());
    }

    #[test]
    fn test_classify_read_result() {
        assert_eq!(classify_read_result(&Ok(64)), ReaderReadResult::Bytes(64));
        assert_eq!(classify_read_result(&Ok(0)), ReaderReadResult::Eof);

        let broken_pipe = std::io::Error::from(ErrorKind::BrokenPipe);
        assert_eq!(
            classify_read_result(&Err(broken_pipe)),
            ReaderReadResult::ExpectedClose
        );

        let perm_denied = std::io::Error::from(ErrorKind::PermissionDenied);
        assert!(matches!(
            classify_read_result(&Err(perm_denied)),
            ReaderReadResult::UnexpectedError(_)
        ));
    }

    #[test]
    fn test_exit_guard_one_shot() {
        let guard = Arc::new(AtomicBool::new(false));
        // First attempt swaps from false to true -> allowed
        assert!(!guard.swap(true, Ordering::SeqCst));
        // Second attempt returns previous value (true) -> rejected
        assert!(guard.swap(true, Ordering::SeqCst));
        // Third attempt also rejected
        assert!(guard.swap(true, Ordering::SeqCst));
    }

    #[test]
    fn test_output_payload_preserves_arbitrary_non_utf8_bytes() {
        let non_utf8 = vec![0x00, 0x1b, 0xff, 0x80, b'A'];
        let event = TerminalOutputEvent {
            session_id: "sess-abc".to_string(),
            data: non_utf8.clone(),
        };

        let serialized = serde_json::to_string(&event).unwrap();
        let deserialized: TerminalOutputEvent = serde_json::from_str(&serialized).unwrap();
        assert_eq!(deserialized.data, non_utf8);
    }

    #[test]
    fn test_error_code_mapping() {
        assert_eq!(
            TerminalError::SessionNotFound("s".into()).error_code(),
            "SESSION_NOT_FOUND"
        );
        assert_eq!(
            TerminalError::EmptyPayload.error_code(),
            "EMPTY_PAYLOAD"
        );
        assert_eq!(
            TerminalError::PayloadTooLarge {
                size: 100,
                max: 50
            }
            .error_code(),
            "PAYLOAD_TOO_LARGE"
        );
        assert_eq!(
            TerminalError::LockPoisoned("lock".into()).error_code(),
            "LOCK_POISONED"
        );
    }

    #[test]
    fn test_reader_setup_failure_cleans_up_session() {
        let manager = TerminalSessionManager::new();
        let session = manager
            .create_session(CreateTerminalSessionInput {
                cols: Some(80),
                rows: Some(24),
                ..Default::default()
            })
            .expect("create session failed");

        let session_id = session.session_id.clone();
        assert!(manager.session_info(&session_id).is_ok());

        // Simulate reader setup failure rollback:
        let rollback_res = manager.close(CloseTerminalSessionInput {
            session_id: session_id.clone(),
        });
        assert!(rollback_res.is_ok());

        // Session must no longer exist:
        assert!(matches!(
            manager.session_info(&session_id),
            Err(TerminalError::SessionNotFound(_))
        ));
    }
}
